CREATE TABLE IF NOT EXISTS `posts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` BIGINT NOT NULL,
  `text` TEXT NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
  ON UPDATE CASCADE
  ON DELETE RESTRICT
);
